name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feature']
  - title: '🐛 Bug Fixes'
    labels: ['bug']
  - title: '🧹 Chores'
    labels: ['chore']
change-template: '- $TITLE @${AUTHOR} (#$NUMBER)'
change-title-escapes: "\""
no-changes-template: '- No changes'
template: |
  ## What's Changed
  $CHANGES
