name: Build and send diploma thesis
description: GitHub action to build and send a diploma thesis using the corresponding Docker image from school HTL Leoben
author: bitsneak
branding:
  icon: mail
  color: yellow

inputs:
  thesis-path:
    description: The path from the repository root to the filled out diploma thesis folder. If not set it will default to 'Diplomarbeit'
    default: Diplomarbeit
    required: false
  dockerhub-username:
    description: The DockerHub username for the image. If not set it will default to 'bytebang'
    default: bytebang
    required: false
  dockerhub-repository:
    description: The DockerHub repository name for the image. If not set it will default to 'htlle-da-env'
    default: htlle-da-env
    required: false
  mail-body:
    description: The body to sent with the email. If not set it will default to the commit message
    required: false
  manual-mode:
    description: If the repository should not be checked out automatically specify the complete workspace path to the thesis-path. If not set it will default to checking out the latest repository state
    required: false

  smtp-server:
    description: The SMTP server of the sending email
    required: true
  smtp-port:
    description: The SMTP server port of the sending email
    required: true
  mail-address:
    description: The sending email address
    required: true
  mail-address-password:
    description: The password for the sending email address
    required: true
  teams-mail:
    description: The email address of the teams channel the diploma thesis is sent to
    required: true

runs:
  using: composite

  steps:
    - name: Checkout repository
      if: ${{ !inputs.manual-mode }}
      uses: actions/checkout@v4

    - name: Set thesis path from manual-mode
      if: ${{ inputs.manual-mode }}
      shell: bash
      run: echo "thesis-path=${{ inputs.manual-mode }}" >> $GITHUB_ENV

    - name: Check if template folder is present
      shell: bash
      run: ls -la ${{ inputs.thesis-path }}/HTLLE-DA-Vorlage

    - name: Cache Docker image
      id: cache-docker
      uses: actions/cache@v4
      with:
        path: /tmp/.docker
        key: docker-${{ inputs.dockerhub-username }}-${{ inputs.dockerhub-repository }}-${{ hashFiles('**/HTLLE-DA-Vorlage/tools/docker/Dockerfile') }}
        restore-keys: | 
          docker-${{ inputs.dockerhub-username }}-${{ inputs.dockerhub-repository }}

    - name: Create Docker cache directory
      if: steps.cache-docker.outputs.cache-hit != 'true'
      shell: bash
      run: mkdir -p /tmp/.docker

    - name: Load cached Docker image
      if: steps.cache-docker.outputs.cache-hit == 'true'
      shell: bash
      run: docker load -i /tmp/.docker/image.tar

    - name: Pull Docker image
      if: steps.cache-docker.outputs.cache-hit != 'true'
      shell: bash
      run: |
        docker pull ${{ inputs.dockerhub-username }}/${{ inputs.dockerhub-repository }}
        docker save ${{ inputs.dockerhub-username }}/${{ inputs.dockerhub-repository }} -o /tmp/.docker/image.tar

    - name: Build diploma thesis
      shell: bash
      run: docker run -v ${{ github.workspace }}/${{ inputs.thesis-path }}:/workspace ${{ inputs.dockerhub-username }}/${{ inputs.dockerhub-repository }}

    - name: Extract commit message
      if: ${{ inputs.mail-body == '' }}
      shell: bash
      run: echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV   

    - name: Send diploma thesis
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: ${{ inputs.smtp-server }}
        server_port: ${{ inputs.smtp-port }}
        username: ${{ inputs.mail-address }}
        password: ${{ inputs.mail-address-password }}
        subject: "Diploma thesis"
        body: ${{ inputs.mail-body || env.commit_message }}
        to: ${{ inputs.teams-mail }}
        from: ${{ inputs.mail-address }}
        attachments: ${{ inputs.thesis-path }}/diplomarbeit.pdf
