name: Feature request
description: Suggest a new idea or improvement for the project.
title: "✨ [Feature Request]: <title>"
labels:
  - enhancement

body:
  - type: input
    id: overview
    attributes:
      label: Overview
      description: Provide a short description of the feature.
      placeholder: Add support for...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the feature or enhancement.
      placeholder: Describe the problem this feature will solve or the functionality it will add.
    validations:
      required: true

  - type: checkboxes
    id: additional_context
    attributes:
      label: Additional Context
      description: Select any additional context that applies.
      multiple: true
      options:
        - label: Improves user experience
        - label: Enhances performance
        - label: Aligns with project goals
      validations:
        required: true

  - type: textarea
    id: potential_implementation
    attributes:
      label: Potential Implementation
      description: Suggest how this feature could be implemented.
      placeholder: The feature could be implemented by...
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Add any other notes or comments you think are relevant.
      placeholder: Any additional detail about the request.
    validations:
      required: false
