name: Build and Send Diplomathesis

on:
  push:
    branches:
      - main
    paths:
      - Diplomarbeit/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git build-essential make-guile texlive-full pandoc pandoc-citeproc tree rsync hunspell hunspell-de-at

          
      - name: Build DA-Thesis
        run: |
          make pdf -C HTLLE-DA-Vorlage SOURCEDIR=../Diplomarbeit/


      - name:  Send File via Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_MAIL }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "Diploma thesis"
          body: " "
          to: ${{ secrets.TEAMS_MAIL }}
          from: ${{ secrets.GMAIL_MAIL }}
          attachments: Diplomarbeit/diplomarbeit.pdf
