name: Testing git tag version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
        - name: Latest tag
          uses: actions-ecosystem/action-get-latest-tag@v1.6.0
          id: get-latest-tag

        - name: Print latest tag
          run: ${{ steps.get-latest-tag.outputs.tag }}
