name: Build and send diploma thesis

on:
  push:
    branches:
      - main
    paths:
      - Diplomarbeit/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build diploma thesis
        run: |
          docker run -v ${{ github.workspace }}/Diplomarbeit:/workspace bytebang/htlle-da-env

      - name: Send diploma thesis
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.MAIL }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Diploma thesis"
          body: " "
          to: ${{ secrets.TEAMS_MAIL }}
          from: ${{ secrets.MAIL }}
          attachments: Diplomarbeit/diplomarbeit.pdf
