name: Build and send diploma thesis

on:
  push:
    branches:
      - main
    paths:
      - Diplomarbeit/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Docker image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/.docker
          key: docker-htlle-da-env }}
          restore-keys: |
            docker-htlle-da-env

      - name: Load cached Docker image
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: docker load -i /tmp/.docker/image.tar

      - name: Pull Docker image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          docker pull bytebang/htlle-da-env
          docker save bytebang/htlle-da-env -o /tmp/.docker/image.tar

      - name: Build diploma thesis
        run: docker run -v ${{ github.workspace }}/Diplomarbeit:/workspace bytebang/htlle-da-env

      - name: Send diploma thesis
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.MAIL }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Diploma thesis"
          body: " "
          to: ${{ secrets.TEAMS_MAIL }}
          from: ${{ secrets.MAIL }}
          attachments: Diplomarbeit/diplomarbeit.pdf
