name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install github-changelog-generator
        run: gem install github_changelog_generator

      - name: Generate Changelog for Latest Tag
        run: |
          LATEST_TAG=${{ github.ref_name }}
          
          github_changelog_generator \
            --user ${{ github.repository_owner }} \
            --project ${{ github.event.repository.name }} \
            --token ${{ secrets.GH_PAT }} \
            --since-tag $(git describe --tags --abbrev=0) \
            --tag-prefix v \
            --output changelog.txt

      - name: Read Changelog Into Variable
        id: changelog
        run: |
          echo "changelog<<EOF" >> $GITHUB_ENV
          cat changelog.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: ${{ env.changelog }}
