name: Release

on:
  push:
    branches:
      - main
    #paths:
      #- .github/package.yml

permissions:
  contents: write

jobs:
  changelog:
    name: Changelog
    if: github.event_name != 'pull_request' 
    runs-on: ubuntu-latest

    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      tag: ${{ steps.changelog.outputs.tag }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      version: ${{ steps.changelog.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Changelog
        uses: TriPSs/conventional-changelog-action@v6
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-user-name: "github-actions"
          git-user-email: "github-actions@users.noreply.github.com"
          skip-git-pull: true
          skip-on-empty: false
          preset: conventionalcommits
          input-file: CHANGELOG.md
          output-file: CHANGELOG.md
          version-file: .github/package.yml
          
  release:
    name: Release
    needs: changelog
    if: github.event_name != 'pull_request' && needs.changelog.outputs.skipped == 'false'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        if: steps.changelog.outputs.skipped != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ needs.changelog.outputs.tag }}
          release_name: ${{ needs.changelog.outputs.tag }}
          body: ${{ needs.changelog.outputs.clean_changelog }}
