name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install github-changelog-generator
        run: gem install github_changelog_generator

      - name: Get The Previous Tag
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0)
          echo "Previous tag: $PREV_TAG"
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV

      - name: Generate Changelog
        run: |
          github_changelog_generator \
            --user bitsneak \
            --project HTLLE-DA-Vorlage \
            --token ${{ secrets.GH_PAT }} \
            --enhancement-labels "enhancement, Enhancement, feat, Feat" \
            --bug-labels "bug, Bug, fix, Fix" \
            --breaking-labels "breaking, Breaking, BREAKING" \
            --security-labels "security, Security" \
            --removed-labels "removed, Removed" \
            --deprecated-labels "deprecated, Deprecated" \
            --unreleased-label "Unreleased" \
            --exclude-labels "duplicate, question, invalid, wontfix" \
            --header-label "# Changelog" \
            --output changelog.txt

      - name: Read Changelog Into Variable
        id: changelog
        run: |
          echo "changelog<<EOF" >> $GITHUB_ENV
          cat changelog.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: ${{ env.changelog }}
