name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read README.md
        id: read_readme
        run: |
          README_CONTENT=$(cat README.md)
          ESCAPED_CONTENT=$(echo "$README_CONTENT" | sed 's/[&/\]/\\&/g' | sed 's/\$/\\$/g')
          echo "$ESCAPED_CONTENT" > $GITHUB_ENV

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: ${{ env.README_CONTENT }}
