name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Release-Please
        run: npm install -g release-please

      - name: Create GitHub Release
        run: |
          release-please github-release \
            --token=${{ secrets.GH_PAT }} \
            --repo-url=${{ github.repository }} \
            --target-branch=main \
            --release-type=simple

      - name: Commit Updated CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(release): update CHANGELOG.md for ${{ github.ref_name }}"
          file_pattern: CHANGELOG.md
