name: Test template 
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Diplomarbeit folder
        run: |
          mkdir Diplomarbeit
          mkdir Diplomarbeit/HTLLE-DA-Vorlage
          cp -r example/* Diplomarbeit/
          cp -r style tools Jenkinsfile Makefile Diplomarbeit/HTLLE-DA-Vorlage
  
      - name: Debug output
        run: |
          echo "Diplomarbeit directory structure:"
          tree Diplomarbeit

      - name: Cache Docker image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/.docker
          key: docker-${{ secrets.DOCKERHUB_USERNAME }}-${{ secrets.DOCKERHUB_REPOSITORY }}-${{ hashFiles('**/HTLLE-DA-Vorlage/tools/docker/Dockerfile') }}
          restore-keys: | 
            docker-${{ secrets.DOCKERHUB_USERNAME }}-${{ secrets.DOCKERHUB_REPOSITORY }}

      - name: Create Docker cache directory
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: mkdir -p /tmp/.docker

      - name: Load cached Docker image
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: docker load -i /tmp/.docker/image.tar

      - name: Pull Docker image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }} -o /tmp/.docker/image.tar

      - name: Build diploma thesis
        run: docker run -v ${{ github.workspace }}/Diplomarbeit:/workspace ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}

        
