name: Test Template

on:
  push:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/**
      - LICENSE
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md
      - SECURITY.md
      - action.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Diploma Thesis Folder
        run: |
          mkdir Diplomarbeit
          mkdir Diplomarbeit/HTLLE-DA-Vorlage
          cp -r example/* Diplomarbeit/
          cp -r style tools Jenkinsfile Makefile Diplomarbeit/HTLLE-DA-Vorlage

      - name: Cache Docker Image
        id: cache-docker
        uses: actions/cache@v4
        with:
          path: /tmp/.docker
          key: docker-${{ secrets.DOCKERHUB_USERNAME }}-${{ secrets.DOCKERHUB_REPOSITORY }}-${{ hashFiles('**/HTLLE-DA-Vorlage/tools/docker/Dockerfile') }}
          restore-keys: | 
            docker-${{ secrets.DOCKERHUB_USERNAME }}-${{ secrets.DOCKERHUB_REPOSITORY }}

      - name: Create Docker Cache Directory
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: mkdir -p /tmp/.docker

      - name: Load Cached Docker Image
        if: steps.cache-docker.outputs.cache-hit == 'true'
        run: docker load -i /tmp/.docker/image.tar

      - name: Pull Docker Image
        if: steps.cache-docker.outputs.cache-hit != 'true'
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}
          docker save ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }} -o /tmp/.docker/image.tar

      - name: Build Diploma Thesis
        run: docker run -v ${{ github.workspace }}/Diplomarbeit:/workspace ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}

        
